/* Write your T-SQL query statement below */
SELECT P.product_name,SUM(UNIT) AS unit
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE MONTH(ORDER_DATE)=02 AND YEAR(ORDER_DATE)=2020
GROUP BY  PRODUCT_NAME
HAVING SUM(UNIT)>=100